# Generated by Django 3.1.3 on 2022-10-06 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anwer',
            new_name='Answer',
        ),
    ]
