# Generated by Django 3.1.3 on 2022-11-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0006_auto_20221107_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='create_date',
            field=models.DateField(),
        ),
    ]
