# Generated by Django 3.1.3 on 2022-11-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0007_auto_20221107_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='create_date',
            field=models.DateField(),
        ),
    ]
